firefox:
    wasm-pack test --headless --firefox
build:
    #export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/usr/include
    wasm-pack build
publish:
    wasm-pack publish
